apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: alpha
        url: https://kubernetes.default.svc
      - cluster: beta
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.cluster}}-'
    spec:
      project: '{{.cluster}}'
      source:
        repoURL: https://github.com/programmeryaml/gitops.git
        targetRevision: HEAD
        path: '{{.cluster}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd