apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  project: alpha
  source:
    - repoURL: 'https://helm.github.io/examples'
      targetRevision: main
      helm:
        valueFiles:
        - $alpha/chart/values.yaml
    - repoURL: "https://github.com/programmeryaml/gitops.git"
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: alpha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true