apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd  # Ensure you specify the namespace where ArgoCD is installed
spec:
  project: beta
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'  # Bitnami repository for Nginx
    targetRevision: main  # Use the appropriate version or branch
    chart: nginx  # Specify the chart name
    helm:
      valueFiles:
        - beta/chart/values.yaml  # Path to your custom values file
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: beta  # Specify the target namespace for deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true